learning_log/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),


]

learning_logs/urls.py
"""Defines URL patterns for learning_logs. """

from django.urls import path
from django.conf.urls import handler404, handler500, handler403, handler400
from learning_logs import views

app_name = 'learning_logs'

handler404 = 'learning_logs.views.error_404_view'
handler500 = 'learning_logs.views.error_500_view'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # About page
    path('about/', views.about, name='about'),
    # Page that shows all topics.
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page for editing an entry.
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    # Page to view charts.
    path('charts/', views.charts, name='charts'),
    # Page for starting a workout.
    path('start_workout/', views.start_workout, name='start_workout'),
    # Page for creating workout cards
    path('new_workout/', views.new_workout, name='new_workout'),
    # Page to all your workout cards created
    path('workouts/', views.workouts, name='workouts'),
    # Detail page for a single workout
    path('workout/<int:workout_id>/', views.workout, name='workout'),
    # Page that notifies entry has been deleted
    path('delete_entry/<int:entry_id>/',
         views.delete_entry, name='delete_entry'),
    # Page that notifies topic has been deleted
    path('delete_topic/<int:topic_id>/',
         views.delete_topic, name='delete_topic'),
    # Page that notifies workout has been deleted
    path('delete_workout/<int:workout_id>/',
         views.delete_workout, name='delete_workout'),
    # Page for home dashboard when you login
    path('home_dash/', views.home_dash, name='home_dash'),
    # Page for editing workouts
    path('edit_workout/<int:workout_id>/',
         views.edit_workout, name='edit_workout'),
    # Page for 404
    path('new_workout_deck/', views.new_workout_deck, name='new_workout_deck'),
    # Page for deleted workout in deck
    path('delete_workout_deck/<int:workout_id>/', views.delete_workout_deck, name='delete_workout_deck'),

]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

learning_logs/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.utils import timezone
# Create your models here.


class Topic(models.Model):
    """A topic the user is learning about. """

    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.date_added <= now

    def __str__(self):
        """Return a string representation of the model. """
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic."""

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)

    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.text[:50]}..."


class WorkoutCard(models.Model):
    """A customizable workout card"""

    name = models.CharField(max_length=200)
    sets = models.IntegerField()
    reps = models.IntegerField()
    pr_met = models.BooleanField(default=False)
    sets_completed = models.IntegerField()
    reps_completed = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.name[:50]}..."

    def details(self):

        return f"{self.name, self.sets, self.reps, self.owner}"


class WorkoutDeck(models.Model):
    """A customizable workout deck to place Workout cards """

    workouts_built_deck = models.ForeignKey(
        WorkoutCard, on_delete=models.CASCADE)
    text = models.TextField(blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

learning_logs/forms.py
from django import forms

from .models import Topic, Entry, WorkoutCard, WorkoutDeck


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ' '}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}


class WorkoutForm(forms.ModelForm):
    class Meta:
        model = WorkoutCard
        fields = ['name', 'sets', 'reps', 'pr_met',
                  'sets_completed', 'reps_completed']
        labels = {'name': 'Name', 'sets': 'Sets', 'reps': 'Reps', 'pr_met': '<-- Check if you made your PR Today in this workout',
                  'sets_completed': 'Sets you were able to complete', 'reps_completed': 'Reps you were able to complete', }


class WorkoutDeckForm(forms.ModelForm):
    class Meta:
        model = WorkoutDeck
        workouts = WorkoutCard.objects.filter().order_by('date_added')
        workouts_details = [""]
        fields = ['workouts_built_deck', 'text']
        labels = {'text': workouts_details}
        widgets = {'text': forms.HiddenInput()}

learning_logs/views.py
import json

from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse, JsonResponse
from django.db.models import Sum
from .models import Topic, Entry, WorkoutCard, WorkoutDeck
from .forms import TopicForm, EntryForm, WorkoutForm, WorkoutDeckForm
from polls.models import Choice, Question
from django.shortcuts import redirect
from json import dumps
from django.views.generic import TemplateView

# Pages section


def index(request):
    """The home page for Learning Log."""

    return render(request, 'learning_logs/index.html')

def about(request):
    """The about me page."""

    return render(request, 'learning_logs/about.html')


@login_required()
def home_dash(request):
    """The main dashboard for users"""
    return render(request, 'learning_logs/home_dash.html')


def check_owner(request, topic_id):

    topic = topic_id
    # Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        return render(request, 'learning_logs/404.html')


@login_required()
def topic(request, topic_id):
    """Show a single topic and all its entries. """
    try:
        topic = Topic.objects.get(id=topic_id)
        check_owner(request, topic)

        entries = topic.entry_set.order_by('-date_added')
        context = {'topic': topic, 'entries': entries}
        return render(request, 'learning_logs/blogging/topic.html', context)
    except entries.DoesNotExist:
        return (request, 'learning_logs/404.html')


@login_required()
def delete_topic(request, topic_id):
    """Delete topic and all its entries. """
    topic = Topic.objects.get(id=topic_id)

    topic.delete()
    context = {}
    return render(request, 'learning_logs/blogging/delete_topic.html', context)


@login_required()
def topics(request):
    """Show all topics."""
    context = 'latest_topic_list'
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/blogging/topics.html', context)


@login_required()
def check_topics(request, duplicate):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    copy = ""
    copy = str(duplicate)
    nw_copy = copy.strip().lower()
    copy_topics = []

    print("~~~~~~~~~~~~")
    print(nw_copy)
    print("~~~~~~~~~~~~~~~~~")
    for topic in topics:
        tp_copy = str(topic.text)
        nw_tp_copy = tp_copy.lower()
        copy_topics.append(nw_tp_copy)

    for topic in copy_topics:

        if nw_copy == topic:
            print("CAN'T HAVE DUPLICATE TOPIC")
            return True


@login_required()
def new_topic(request):
    """Add a new topic."""

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)

        if form.is_valid():

            new_topic = form.save(commit=False)

            # Check to make sure no duplicate topic is made
            if check_topics(request, new_topic) == True:
                return redirect('/new_topic/')
            new_topic.owner = request.user
            new_topic.save()

            return redirect('learning_logs:topics')
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'learning_logs/blogging/new_topic.html', context)


@login_required()
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    check_owner(request, topic)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/blogging/new_entry.html', context)


@login_required()
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # Make sure the proper owner is the one editing.
    check_owner(request, topic)

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.

        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/blogging/edit_entry.html', context)


@login_required()
def delete_entry(request, entry_id):
    """Delete an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # Make sure the proper owner is the one editing.
    check_owner(request, topic)

    entry.delete()
    context = {'entry': entry, 'topic': topic}
    return render(request, 'learning_logs/blogging/delete_entry.html', context)


@login_required()
def start_workout(request):
    workouts = WorkoutCard.objects.filter(
        owner=request.user).order_by('date_added')
    workout_deck = WorkoutDeck.objects.filter(
        owner=request.user).order_by('date_added')
    context = {'workouts': workouts, 'workout_deck': workout_deck}
    return render(request, 'learning_logs/fitness/start_workout.html', context)


@login_required()
def edit_workout(request, workout_id):
    """Edit an existing entry."""
    workout = WorkoutCard.objects.get(id=workout_id)

    # Make sure the proper owner is the one editing.
    check_owner(request, workout)

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.

        form = WorkoutForm(instance=workout)
    else:
        # POST data submitted; process data.
        form = WorkoutForm(instance=workout, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:workout', workout_id=workout.id)
    context = {'workout': workout, 'form': form}
    return render(request, 'learning_logs/fitness/edit_workout.html', context)


@login_required()
def new_workout(request):
    """Add a new workout."""
    workouts = WorkoutCard.objects.filter(
        owner=request.user).order_by('date_added')
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = WorkoutForm()
    else:
        # POST data submitted; process data.
        form = WorkoutForm(data=request.POST)

        if form.is_valid():

            new_topic = form.save(commit=False)

            # Check to make sure no duplicate topic is made
            if check_topics(request, new_topic) == True:
                return redirect('/new_topic/')
            new_topic.owner = request.user
            new_topic.save()

            return redirect('learning_logs:workouts')
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'learning_logs/fitness/new_workout.html', context)


@login_required()
def workout(request, workout_id):
    """Show a single workout card. """
    workout = WorkoutCard.objects.get(id=workout_id)

    context = {'workout': workout}
    return render(request, 'learning_logs/fitness/workout.html', context)


@login_required()
def workouts(request):
    """Show all workouts."""
    workouts = WorkoutCard.objects.filter(
        owner=request.user).order_by('date_added')
    workout_deck = WorkoutDeck.objects.filter(
        owner=request.user).order_by('date_added')
    context = {'workouts': workouts, 'workout_deck': workout_deck}
    return render(request, 'learning_logs/fitness/workouts.html', context)


@login_required()
def new_workout_deck(request):
    """ 
    Create a workout deck.
    """
    # POST data submitted; process data.
    form = WorkoutDeckForm(data=request.POST)

    if form.is_valid():

        new_deck = form.save(commit=False)
        new_deck.owner = request.user
        new_deck.text = new_deck.workouts_built_deck.details()
        new_deck.save()

        return redirect('learning_logs:workouts')

        # Check to make sure no duplicate topic is made

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'learning_logs/fitness/new_workout_deck.html', context)

@login_required()
def delete_workout_deck(request, workout_id):
    """Delete a workout"""
    workout = WorkoutDeck.objects.get(id=workout_id)

    workout.delete()
    context = {}
    return render(request, 'learning_logs/fitness/delete_workout.html', context)


@login_required()
def delete_workout(request, workout_id):
    """Delete a workout"""
    workout = WorkoutCard.objects.get(id=workout_id)

    workout.delete()
    context = {}
    return render(request, 'learning_logs/fitness/workouts.html', context)


"""
TODO: see about moving charts to Models and read from the DB instead of bloating view.
"""



@login_required()
def charts(request):

    def charts_view():
        q = Question.objects.get(pk=1)

        color_name = []
        context = {}

        color_name.append(q.choice_set.all())
        print(color_name)

        blue = str(color_name[0][0])
        red = str(color_name[0][1])
        orange = str(color_name[0][2])
        green = str(color_name[0][3])
        purple = str(color_name[0][4])
        yellow = str(color_name[0][5])
        black = str(color_name[0][6])
        white = str(color_name[0][7])
        pink = str(color_name[0][8])

        bv = color_name[0][0].votes
        rv = color_name[0][1].votes

learning_logs/templates/learning_logs/blogging/delete_entry.html
{% extends "learning_logs/base.html" %} 
{% load bootstrap4 %} 
{% block page_header %}
<h1>
  <a
    href="{% url 'learning_logs:topic' topic.id %}"
    role="button"
    class="button-chart-on"
    >Back to entries &raquo;</a
  >
</h1>
<br />
<div class="alert alert-success" role="alert">Entry deleted!</div>
{% endblock page_header %}

learning_logs/templates/learning_logs/blogging/delete_topic.html
{% extends "learning_logs/base.html" %} 
{% load bootstrap4 %} 
{% block page_header %}
<h1>
  <button
    class="button-chart-on"
    onclick="window.location.href={% url 'learning_logs:topics' %}"
  >
    Back to topics &raquo;
  </button>
</h1>
<br />
<div class="alert alert-success" role="alert">Topic deleted!</div>
{% endblock page_header %}

learning_logs/templates/learning_logs/blogging/edit_entry.html
{% extends "learning_logs/base.html" %} 
{% load bootstrap4 %} 
{% block page_header %}
<h1><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h1>
{% endblock page_header %} {% block content %}
<form
  method="post"
  action="{% url 'learning_logs:edit_entry' entry.id %}"
  class="form"
>
  {% csrf_token %} {% bootstrap_form form %} {% buttons %}
  <p><button name="submit" class="button-chart-on">Save changes</button></p>
  {% endbuttons %}

  <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
</form>

{% endblock content %}

learning_logs/templates/learning_logs/blogging/new_entry.html
{% extends "learning_logs/base.html" %} 
{% load bootstrap4 %} 
{% block page_header %}
<h2>Add a new entry to: {{ topic }}</h2>
{% endblock page_header %} 
{% block content %}

<form action="{% url 'learning_logs:new_entry' topic.id %}" method="post" >
  {% csrf_token %} {% bootstrap_form form %} {% buttons %}
  <button name="submit" class="button-chart-on">Save entry</button>
  {% endbuttons %}
  <input type="hidden" name="next" value="{% url 'learning_logs:topics' %}" />
</form>

{% endblock content %}

learning_logs/templates/learning_logs/blogging/new_topic.html
{% extends "learning_logs/base.html" %} 
{% load bootstrap4 %} 
{% block page_header %}
<h2>Add a new topic</h2>
{% endblock page_header %} {% block content %}

<form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">
  {% csrf_token %} {% bootstrap_form form %} {% buttons %}

  <button name="submit" class="button-chart-on">Save</button>
  {% endbuttons %}
  <input type="hidden" name="next" value="{% url 'learning_logs:topics' %}" />
</form>

{% endblock content %}

learning_logs/templates/learning_logs/blogging/topic.html
{% extends 'learning_logs/base.html' %} 
{% block page_header %}
<h3>{{ topic }}</h3>

{% endblock page_header %} 
{% block content %}

<ul>
  {% for entry in entries %}
  <div class="card mb-3">
    <h4 class="card-header">
      {{ entry.date_added|date:'M d, Y H:i' }}
      <small
        ><a
          class="btn btn-sm btn-warning"
          href="{% url 'learning_logs:edit_entry' entry.id%}"
          role="button"
        >
          edit entry
        </a></small
      >
      <small
        ><a
          class="btn btn-sm btn-danger"
          href="{% url 'learning_logs:delete_entry' entry.id%}"
          role="button"
          >delete entry</a
        ></small
      >
    </h4>
    <div class="card-body" id="blue-bg">{{ entry.text|linebreaks }}</div>
  </div>
  {% empty %}
  <h4 id="light-gray-bg" class="card-header txt-white">
    There are no entries for this topic yet.
  </h4>
  <br />
  {% endfor %}

  <div>

    <a class="button-chart-on" href="{% url 'learning_logs:new_entry' topic.id%}" role="button">
      Add entry
    </a>
   
  </div>
</ul>

{% endblock content %}

learning_logs/templates/learning_logs/blogging/topics.html
{% extends "learning_logs/base.html" %}
{% block page_header %}
<h3 class="card-header" >Topics</h3>
{% endblock page_header %}

{% block content %}

<ul >
    {% for topic in topics %}
    <div class="card mb-3" >
        <a href="{% url 'learning_logs:topic' topic.id%}">
        <h4 class="card-header" >
                {{ topic }}
        </h4>
        <br>
        <p style="padding-left: 15px;"><a class="btn btn-lg btn-danger" href="{% url 'learning_logs:delete_topic' topic.id%}" role="button" >Delete</a></p>
    </a>
</div>
    {% empty %}
    <h4 class="card-header" id="light-gray-bg"><p>There are no entries for this topic yet.</p></h4>
    {% endfor %}
</ul>
<p>  
     <button class="button-chart-on" onclick="window.location.href={% url 'learning_logs:new_topic' %}">Add a topic</button>

</p>

{% endblock content %}